fix(pull_request.yml): add conditional steps for success and failure handling to improve workflow clarity and control over auto merge process

diff --git a/.github/workflows/pull_request.yml b/.github/workflows/pull_request.yml
--- a/.github/workflows/pull_request.yml
+++ b/.github/workflows/pull_request.yml
@@ -15,6 +15,19 @@ jobs:
   success:
     runs-on: ubuntu-latest
     needs: [ build ]
+    if: ${{ always() }}
     steps:
+      - name: "Debug each needs.build.result"
+        run: echo "needs.build.result ${{ needs.build.result }}"
+
       - name: "✅ Success"
+        if: ${{ needs.build.result == 'success' }}
         run: echo "::notice title={Success}::This step triggers auto merge if all dependencies are met."
+
+      - name: "❌ Failure"
+        if: ${{ needs.build.result != 'success' }}
+        run: |
+          echo "::error title={Failure}::This step stops the auto merge process."
+          exit 1
+    outputs:
+      success: "true"
